replicaCount: 1

environment: staging

image:
  repository: nginx
  tag: "ade62a90a1e4642fef2f9960c7df5a5efd0cfcc2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

config:
  appEnv: staging
  appMessage: "Hello from Helm Staging"
