replicaCount: 1

environment: development

image:
  repository: europe-west2-docker.pkg.dev/lawal-project-84096/kubernetes-gitops-platform/web-app
  tag: "cb9b90a8e1681fdb8bf4a21fa318f6e9592abce7"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

config:
  appEnv: development
  appMessage: "Hello from Helm Dev"
